### ISSUE TITLE
Throws for all swaggers I've tried

### ISSUE THREAD

**Issue by frankhaugen** [CenterEdge/Yardarm#161]
I must be doing something wrong because it's throwing for anything. Heres the Swaggers of the APIs I've tried to make work:

> https://api.fiken.no/api/v2/docs/swagger.yaml  
> https://api.semine.no/swagger/v1.0/swagger.json  
> https://api.tripletex.io/v2/swagger.json

My code, (running in LinqPad 7):
```csharp
var reader = new Microsoft.OpenApi.Readers.OpenApiStreamReader();
var document = reader.Read(Downloader.Download("https://api.fiken.no/api/v2/docs/swagger.yaml"), out _);
var settings = new YardarmGenerationSettings();
var generator = new Yardarm.YardarmGenerator(document, settings);
var result = await generator.EmitAsync();
```

I might be doing something wrong, (solution should have a demo-project)

**Comment by brantburnett** [comment]
Your problem is most likely that you don't have sufficient settings in YardarmGenerationSettings, such as the output file stream. You can find an example of how to fill the settings from the command line project: https://github.com/CenterEdge/Yardarm/blob/bddef7de3c4d52b3d060e15960de1e03af4a7cb1/src/main/Yardarm.CommandLine/GenerateCommand.cs#L39

I'll be honest, there's no example application because the primary use case (I thought) was via the command line or SDK-project approaches. It's how we use it for all our use cases. Out of curiosity, can you elaborate on your use case for generating via C# calls? I want to make sure I understand the user base so I do a good job of maintaining the project. Thanks!

**Comment by frankhaugen** [comment]
What I am trying to achieve is to generate models and client(s) for APIs that is to my particular standards, (like nesting and, inheritance, namespaces etc.). 

This library, (all five minutes I tried using it), is seemingly perfect.

I will look into it some more and see if I can get it to work.

I'll make it like a sample on my GitHub and post link in this thread if I can make it work for me, and secondly, I'll make notes on usability and give you some real feedback

**Comment by brantburnett** [comment]
I gotcha, so you want to apply so customizations above and beyond what is offered via the command line? That makes sense.

If I'm understanding that correctly, there are basically two different ways to approach it. One is the way you're currently approaching it, and the other would be to create an extension DLL. Either way, I've tried to design it to be as customizable as possible. I'd really love your feedback and I'm happy to help with any questions you may have.

If you use Slack or Discord I can also get you my contact info there.

**Comment by frankhaugen** [comment]
The customization possibilities got me intrigued in this library, as compared to use nswag and then changing it's sub-par code-generation.

I'm tempted to write some wrappings or maybe a fluent-patterned builder that can register code fixers and analyzers, but right now I'm not at a computer so I'm not able to much experimentation.

Feel free to add me on discord: "frankhaugen<HASHTAG>8099" is my discord nick, (it's already published a few places, so I don't fear the web scrapers).
